Numpy Array and Basics

In [1]:
import numpy as np 

CREATING ARRAYS FROM LIST

In [2]:
arr_1D=np.array([1,2,3,4,5,6])
print(arr_1D)

arr_2D=np.array([[1,2,3],[4,5,6]])
print(arr_2D)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


LIST vs NUMPY ARRAY

In [3]:
py_list=[1,2,3,4,5,6]
print("List multiplication: ", py_list*2)

List multiplication:  [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


In [4]:
num_arr=np.array([1,2,3,4,5,6])
print('Numpy arrray multiplication: ', num_arr*2)

Numpy arrray multiplication:  [ 2  4  6  8 10 12]


CREATING ARRAYS FROM SCRATCH

In [6]:
zeros=np.zeros((4,5))
print('Zeros Array: \n', zeros)

Zeros Array: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
ones=np.ones((4,5))
print('Ones Array: \n', ones)

Ones Array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
full=np.full((4,5),7)
print(full)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [10]:
random = np.random.random((2,3))
print(random)

[[0.72520593 0.04877377 0.89651502]
 [0.9879917  0.86008964 0.64634012]]


In [11]:
sequence = np.arange(0,10,2)
print(sequence)

[0 2 4 6 8]


VECTOR, MATRIX AND TENSOR

In [12]:
vector = np.array([1,2,3])
print(vector)

[1 2 3]


In [13]:
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [15]:
tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


ARRAY PROPERTIES

In [17]:
arr = np.array([[1,2,3],[4,5,6]])

print('Shape :', arr.shape) # Gives shape of array(roes and column)
print('Dimension :', arr.ndim) # Give dimension of array(1d,2d, or nd)
print('Size :', arr.size) #Give number of elements in array
print('Datatype :', arr.dtype)    #Give datatype

Shape : (2, 3)
Dimension : 2
Size : 6
Datatype : int64


ARRAY RESHAPING

In [21]:
arr = np.arange(12)
print('Original Array: ', arr)

reshape = arr.reshape((6,2)) #Can reshape the array in desired shape
print('Reshaped Array:\n', reshape)

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [26]:
arr = np.array([[1,2,3],
                [4,5,6]])
print('Original Array:\n', arr)

flatten = arr.flatten() #Flats the array as much as possible
print('Flattened Array: ', flatten)

#Returns: A copy of the original array.
#Changes to the new array will NOT affect the original array.



Original Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array:  [1 2 3 4 5 6]


In [ ]:
tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print('Original:\n',tensor)

flat=tensor.flatten() # As here you can see in output it can also flat tensor(multi dimensional) to 1D
print('Flatten: ', flat)



Original:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Flatten:  [1 2 3 4 5 6 7 8]


In [28]:
arr = np.array([[1,2,3],
                [4,5,6]])
print('Original Array:\n', arr)

rav = arr.ravel() 
print('Raveled Array: ', rav)

Original Array:
 [[1 2 3]
 [4 5 6]]
Raveled Array:  [1 2 3 4 5 6]


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
print('Original Array:\n', arr)

rav = arr.ravel() 
print('Raveled Array: ', rav)

rav[0]=100
print('Original Array after updation in raveled:\n', arr)
print('Raveled Array after updation in raveled: ', rav)

#Returns: A view (if possible) of the original array.
#Changes to the new array might affect the original array (if it's a view).
#As in output you can see when i did changes in original array it also affected the raveled array but in flatten it will not happen

Original Array:
 [[1 2 3]
 [4 5 6]]
Raveled Array:  [1 2 3 4 5 6]
Original Array after updation in raveled:
 [[100   2   3]
 [  4   5   6]]
Raveled Array after updation in raveled:  [100   2   3   4   5   6]


In [32]:
'''Transpose:- Transpose means flipping a matrix over its diagonal i.e. rows becomes columns and columns become rows'''
arr = np.array([[1,2,3],
                [4,5,6]])
print('Original Array:\n', arr)

trans = arr.T
print('Transposed matrix:\n', trans)

Original Array:
 [[1 2 3]
 [4 5 6]]
Transposed matrix:
 [[1 4]
 [2 5]
 [3 6]]
