## Advance Operation with Business Example

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
# Data Structure : [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000], #Paradise Biryani
    [2, 120000, 140000, 160000, 190000], #Beijing Bites
    [3, 200000, 230000, 260000, 300000], #Pizza Hub
    [4, 180000, 210000, 240000, 270000], #Burger Point
    [5, 160000, 185000, 205000, 230000] #Chai Point
])

print('==== Zomato Sales Analysis ====')
print('Sales data Shape', sales_data.shape)


==== Zomato Sales Analysis ====
Sales data Shape (5, 5)


In [12]:
# I want first 3 rows of the data
print('First three rows of the data:\n', sales_data[0:3])

First three rows of the data:
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [13]:
# I want last 4 columns of the data
print('Last 4 columns of the data:\n', sales_data[:, 1:])

Last 4 columns of the data:
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


In [16]:
# I want combined sales of all restaurant per year
comb_sale = np.sum(sales_data[:, 1:], axis=0)
print(comb_sale)

[ 810000  945000 1085000 1240000]


In [18]:
# I want total sales of each restaurant of last 4 years
total_sales = np.sum(sales_data[:, 1:], axis=1)
print(total_sales)

[800000 610000 990000 900000 780000]


In [23]:
# I want minimum sales per restaurant
min_sales = np.min(sales_data[:, 1:], axis=1)
print(min_sales)

[150000 120000 200000 180000 160000]


In [25]:
#I want maximum sales per year (means combined of all restaurant)
max_sales = np.max(sales_data[:, 1: ], axis=0)
print(max_sales)

[200000 230000 260000 300000]
