## NUMPY ARRAY OPERATIONS

In [1]:
import numpy as np 

Slicing

In [5]:
#Slicing means extracting a part(subset) of an array using specific range of index
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print('Basic Slicing: ', arr[2:7])
print('with step: ', arr[1:8:2]) #With step means it will jump the step you give 
print('Negative indexing: ', arr[-9:-4]) # Indexing from behind

Basic Slicing:  [3 4 5 6 7]
with step:  [2 4 6 8]
Negative indexing:  [2 3 4 5 6]


SOME BASIC OPERATION OF 2D ARRAY

In [7]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print('Specific element: ', arr[1,2]) #If i want tp get specific element from 2D array
print('Entire Row: ', arr[1]) #If i want specific entire row from 2D array
print('Entire Column', arr[:, 1]) # if i want apecific entire column from 2D array

Specific element:  6
Entire Row:  [4 5 6]
Entire Column [2 5 8]


SORTING

In [8]:
#Sorting means arranging the elements of array either in aescending or descending order.
arr = np.array([3,5,4,8,6,9,546,78,10,36,5])
print('Original Array: ', arr)
print('Sorted Array: ', np.sort(arr))

Original Array:  [  3   5   4   8   6   9 546  78  10  36   5]
Sorted Array:  [  3   4   5   5   6   8   9  10  36  78 546]


In [14]:
arr = np.array([[4,8,3],
                [2,7,5],
                [0,9,1]])

print('Sorting Column wise:\n', np.sort(arr, axis=0)) # Sorts the elements in each column
print('Sorting Row wise:\n', np.sort(arr, axis=1)) # Sorts the elements in each row

Sorting Column wise:
 [[0 7 1]
 [2 8 3]
 [4 9 5]]
Sorting Row wise:
 [[3 4 8]
 [2 5 7]
 [0 1 9]]


Filter

In [15]:
#Filtering means selecting specific elements from an array based on a condition

arr = np.array([1,2,3,4,5,6,7,8,9,10])
even = arr[arr % 2 == 0]
odd = arr[arr % 2 != 0]
print('Even elements in the array: ', even)
print('Odd elements in the array: ', odd)

Even elements in the array:  [ 2  4  6  8 10]
Odd elements in the array:  [1 3 5 7 9]


In [16]:
# Filtering with mask
arr = np.array([1,2,3,4,5,6,7,8,9,10])
mask = arr > 5
print('Elements greater than 5: ', arr[mask])

Elements greater than 5:  [ 6  7  8  9 10]


FANCY INDEXING vs NP.WHERE()

In [18]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
indices = [0,2,4]
print(arr[indices])

where_result = np.where(arr>5)
print(arr[where_result])

[1 3 5]
[ 6  7  8  9 10]


In [27]:
#Condition Array
'''Logic behind this
if arr>5:
    arr*2
else:
    arr'''

arr = np.array([1,2,3,4,5,6,7,8,9,10])
condi= np.where(arr>5, arr*2, arr)
print(condi)

[ 1  2  3  4  5 12 14 16 18 20]
